name: echo_world
description: my game in flutter flame
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.0.1
  equatable: ^2.0.7
  flame: ^1.32.0
  flame_audio: ^2.11.10
  flame_behaviors: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  video_player: ^2.10.1

dev_dependencies:
  bloc_test: ^10.0.0
  flame_test: ^2.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
  video_player_platform_interface: ^6.6.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
    - assets/img/
    - assets/video/
