name: echo_world
description: Project Cassandra - my game in flutter flame
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  audioplayers: ^6.5.1
  bloc: ^9.0.1
  equatable: ^2.0.7
  flame: ^1.32.0
  flame_audio: ^2.11.10
  flame_behaviors: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.3
  hydrated_bloc: ^10.1.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  video_player: ^2.10.1
  flutter_shaders: ^0.1.3
  supabase_flutter: ^2.10.3

dev_dependencies:
  bloc_test: ^10.0.0
  flame_test: ^2.0.3
  flutter_test:
    sdk: flutter
  mockingjay: ^2.0.0
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^10.0.0
  video_player_platform_interface: ^6.6.0
  flutter_launcher_icons: ^0.14.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/licenses/poppins/
    - assets/img/
    - assets/video/
    - assets/icon/Icon_echo.png
    - assets/levels/walls/wall_1.png
    - assets/levels/skybox/skybox1.jpg
    - assets/minigames/surgery/imagenes/
    - assets/minigames/surgery/descripciones.json
    - assets/enemigos/enemigo_comun.png
    - assets/enemigos/enemigo_cyan.png
    - assets/enemigos/enemigo_purpura.png
    - assets/enemigos/enemigo_rojo.png
    - assets/enemigos/enemigo_verde.png
    - lib/shaders/glitch.frag
    - lib/shaders/pulse.frag

# Configuraci√≥n de flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Icon_echo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/Icon_echo.png"
  windows:
    generate: true
    image_path: "assets/icon/Icon_echo.png"
  macos:
    generate: true
    image_path: "assets/icon/Icon_echo.png"
